stages:

  data_prep:
    cmd: python python/DataPreparation/data_prep.py -id data/raw -od data/prepared -p params.yaml
    deps:
      - python/DataPreparation/data_prep.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_prep

  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree.py -id data/prepared/${argument_pool} -od data/models/${argument_pool} -mn ${key} -p params.yaml
      deps:
        - python/decisionTree/decision_tree.py
        - data/prepared
      outs:
        - data/models/${argument_pool}/${key}.joblib
      params:
        - decision_tree

  decision_tree_valid:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree_valid.py -id data/prepared/${argument_pool}  -im data/models/${argument_pool}/${key}.joblib -mn ${key} -ap ${argument_pool}
      deps:
        - python/decisionTree/decision_tree_valid.py
        - data/prepared
        - data/models/${argument_pool}/${key}.joblib
      metrics:
        - metrics/${argument_pool}/${key}_metrics.json:
            cache: false
      plots:
        - plots/${argument_pool}/${key}_CM.png:
            cache: false

  decision_tree_prod:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -mn ${key} -ap ${argument_pool}
      deps:
        - python/decisionTree/decision_tree_full.py
        - data/prepared
      outs:
        - data/models/${argument_pool}/${key}_prod.joblib

  light_gbm:
    cmd: python python/lightGBM/light_gbm.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -p params.yaml
    deps:
      - python/lightGBM/light_gbm.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/lightGBM.joblib
    params:
      - light_gbm

  light_gbm_valid:
    cmd: python python/lightGBM/light_gbm_valid.py -id data/prepared/${argument_pool}/ -im data/models/${argument_pool}/lightGBM.joblib -mn LightGBM -ap ${argument_pool}
    deps:
      - python/lightGBM/light_gbm_valid.py
      - data/prepared
      - data/models/${argument_pool}/lightGBM.joblib
      - python/decisionTree/decision_tree_valid.py
    metrics:
      - metrics/${argument_pool}/LightGBM_metrics.json:
          cache: false
    plots:
      - plots/${argument_pool}/LightGBM_CM.png:
          cache: false

  light_gbm_prod:
    cmd: python python/lightGBM/light_gbm_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -ap ${argument_pool}
    deps:
      - python/lightGBM/light_gbm_full.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/lightGBM_prod.joblib


  cat_boost:
    cmd: python python/catBoost/cat_boost.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -p params.yaml
    deps:
      - python/catBoost/cat_boost.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/CatClassifier.joblib
    params:
      - cat_boost

  cat_boost_validation:
    cmd: python python/catBoost/cat_boost_valid.py -id data/prepared/${argument_pool}/ -im data/models/${argument_pool}/CatClassifier.joblib -mn CatBoost -ap ${argument_pool}
    deps:
      - python/catBoost/cat_boost_valid.py
      - data/prepared
      - data/models/${argument_pool}/CatClassifier.joblib
    metrics:
      - metrics/${argument_pool}/CatBoost_metrics.json:
          cache: false
    plots:
      - plots/${argument_pool}/CatBoost_CM.png:
          cache: false

  cat_boost_prod_version:
    cmd: python python/catBoost/cat_boost_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/
    deps:
      - python/catBoost/cat_boost_full.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/CatClassifier_prod.joblib

  SVM:
    cmd: python python/svm/svm.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -bpd python/svm/ -p params.yaml
    deps:
      - python/svm/svm.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/svm.joblib
      - python/svm/svm_best.json
    params:
      - svm

  SVM_valid:
    cmd: python python/svm/svm_valid.py -id data/prepared/${argument_pool}/ -im data/models/${argument_pool}/svm.joblib -mn svm -ap ${argument_pool}
    deps:
      - python/svm/svm_valid.py
      - data/models/${argument_pool}/svm.joblib
      - data/prepared
    metrics:
      - metrics/${argument_pool}/svm_metrics.json:
          cache: false
    plots:
      - plots/${argument_pool}/svm_CM.png:
          cache: false

  SVM_prod:
    cmd: python python/svm/svm_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -bpd python/svm/
    deps:
      - python/svm/svm_full.py
      - python/svm/svm_best.json
      - data/prepared
    outs:
      - data/models/${argument_pool}/svm_prod.joblib

  prep_valid_data:
    cmd: python python/DataPreparation/data_prep_new.py -id data/new/raw -od data/new/prepared  -ap ${argument_pool}
    deps:
      - python/DataPreparation/data_prep_new.py
      - data/new/raw
    outs:
      - data/new/prepared

  validation_on_new_data:
    foreach:
      - DecisionTree
      - RandomForest
      - lightGBM
      - CatClassifier
      - svm
    do:
      cmd: python python/validation/valid_new_data.py -id data/new/prepared -im data/models/${argument_pool}/${item}_prod.joblib -mn ${item} -ap ${argument_pool}
      deps:
        - python/validation/valid_new_data.py
        - data/new/prepared
        - data/models/${argument_pool}/${item}_prod.joblib
      metrics:
        - metrics/${argument_pool}/NewData/${item}_metrics.json:
            cache: false
      plots:
        - plots/${argument_pool}/NewData/${item}_CM.png:
            cache: false
