stages:

  data_prep:
    cmd: python python/DataPreparation/data_prep.py -id data/raw -od data/prepared -p params.yaml
    deps:
      - python/DataPreparation/data_prep.py
      - data/raw
    outs:
      - data/prepared
    params:
      - data_prep

  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree.py -id data/prepared/${argument_pool} -od data/models/${argument_pool} -mn ${key} -p params.yaml
      deps:
        - python/decisionTree/decision_tree.py
        - data/prepared
      outs:
        - data/models/${argument_pool}/${key}.joblib
      params:
        - decision_tree

  decision_tree_validation:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree_valid.py -id data/prepared/${argument_pool}  -im data/models/${argument_pool}/${key}.joblib
      deps:
        - python/decisionTree/decision_tree_valid.py
        - data/prepared
        - data/models/${argument_pool}/${key}.joblib

  decision_tree_prod:
    foreach: ${decision_tree}
    do:
      cmd: python python/decisionTree/decision_tree_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -mn ${key} -ap ${argument_pool}
      deps:
        - python/decisionTree/decision_tree_full.py
        - data/prepared
      outs:
        - data/models/${argument_pool}/${key}_prod.joblib

  cat_boost:
    cmd: python python/catBoost/cat_boost.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/ -bm data/models/${argument_pool}/RandomForest_prod.joblib -p params.yaml
    deps:
      - python/catBoost/cat_boost.py
      - data/prepared
      - data/models/${argument_pool}/DecisionTree_prod.joblib
    outs:
      - data/models/${argument_pool}/CatClassifier.joblib
    params:
      - cat_boost

  cat_boost_validation:
    cmd: python python/catBoost/cat_boost_valid.py -id data/prepared/${argument_pool}/ -im data/models/${argument_pool}/CatClassifier.joblib
    deps:
      - python/catBoost/cat_boost_valid.py
      - data/prepared
      - data/models/${argument_pool}/CatClassifier.joblib

  cat_boost_prod_version:
    cmd: python python/catBoost/cat_boost_full.py -id data/prepared/${argument_pool}/ -od data/models/${argument_pool}/
    deps:
      - python/catBoost/cat_boost_full.py
      - data/prepared
    outs:
      - data/models/${argument_pool}/CatClassifier_prod.joblib

  prep_valid_data:
    cmd: python python/DataPreparation/data_prep_new.py -id data/new/raw -od data/new/prepared  -ap ${argument_pool}
    deps:
      - python/DataPreparation/data_prep_new.py
      - data/new/raw
    outs:
      - data/new/prepared

  validation_on_new_data:
    foreach:
      - DecisionTree
      - RandomForest
      - CatClassifier
    do:
      cmd: python python/validation/valid_new_data.py -id data/new/prepared -im data/models/${argument_pool}/${item}_prod.joblib
      deps:
        - python/validation/valid_new_data.py
        - data/new/prepared
        - data/models/${argument_pool}/${item}_prod.joblib
