argument_pool: 'pure-motor-currents'
#['motor-axis-currents', 'motorCurrent-motorVelocities', 'only-motor-currents', 'pure-motor-currents']

data_prep:
  train_test_ratio: 0.7
  train_val_ratio: 0.9
  random_state: 42

decision_tree:
  DecisionTree:
    max_depth: [ 5, 10, 15, 25 ]
    splitter: [ 'best' ]
    min_samples_split: [ 5, 10, 15, 25, 35]
    min_samples_leaf: [ 10, 15, 25, 35 ]
#  DecisionTree:
#    max_depth: [ 7 ]
#    splitter: [ 'best' ]
#    min_samples_leaf: [ 15 ]
#    min_samples_split: [ 10 ]
  RandomForest:
    n_estimators: [ 15, 25, 100]
    max_depth: [ 5, 10, 15, 20, 25 ]
    min_samples_split: [ 15, 25, 35]
    min_samples_leaf: [ 15, 25, 35]

light_gbm:
  max_bin: [100, 255, 355]
  learning_rate: [0.05, 0.1]
  num_iterations: [150, 200]
  num_leaves: [30, 40, 80]
  boosting: ["gbdt", "dart"]
  min_data_in_leaf: [10, 15, 25]


#cat_boost:
#  n_estimators: [ 40, 100 ]
#  max_depth: [ 6, 8, 10 ]
#  min_data_in_leaf: [5, 10, 15, 20, 25]

cat_boost:
  max_depth: [ 8 ]
  min_data_in_leaf: [ 50 ]
  n_estimators: [ 40 ]

svm:
  kernel: ['linear']
  C: [ 1.0]
